application: budgetapp-nick-dani
version: 1
runtime: go
api_version: go1
handlers:
- url: /.*
  script: _go_app
skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^node_modules
